version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3050:80
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/client/node_modules
      - ./client:/usr/client
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/api/node_modules
      - ./api:/usr/api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/worker/node_modules
      - ./worker:/usr/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  postgres:
    image: postgres:latest
  redis:
    image: redis:latest
